### ISSUE TITLE
As of 12 February 2015 it doesn't work. 

### ISSUE THREAD

**Issue by Memoris** [SG57/FFXIV-Nexus-Progress#10]
As the title said, the program doesn't work anymore.

**Comment by SG57** [comment]
Looks like the new patch broke it! I don't have an active sub to fix it myself, but I've walked people thru the process via skype the last few times no problem.

Takes 20 minutes over skype, hit me up if you guys want my help fixing it!

**Comment by SG57** [comment]
I have verified the memory addresses have been working correctly without needing a memory patch.
