### ISSUE TITLE
Can't attach to process again after 2.51 update

### ISSUE THREAD

**Issue by MadCabbit** [SG57/FFXIV-Nexus-Progress#12]
Broken after the update again.  Also, any chance this can be updated to track zeta progress?  It isn't quite as important, since zeta progress is much quicker, but it's a thought.

**Comment by SG57** [comment]
Yup FFXIV getting a 2.6 patch requires the Nexus tracker a memory update of its own.  I will try to do it tonight via skyping a friend who has an account, thanks.

And I have no idea what Zeta or zodiac tracking is, I quit playing when Nexus was tops.  I'd need to play around in memory on an account with a Zodiac working on Zeta progress.  If it's done via spirit bonding again then this could work for it requiring very littile work from me.

**Comment by MadCabbit** [comment]
The light works kind of the same way, the tiers appear to be the same, but the light notifications are stacked differently.  You need to go through 12 mahatmas (200 sold each) one at a time (named similarly to the atmas), and you do a mini light farm for like 40 points on each, for like 480 points total.  Since there's more than one grind per weapon, no way of knowing if they just use the SB info again and just reset it on purchase of a new mahatma, or if they use separate tables.

**Comment by SG57** [comment]
I see, yes definitely would require poking in memory sadly I don't have an active sub so I cannot at least not directly.

**Comment by SG57** [comment]
In any case, the memory addresses are updated for 2.51, let me know if there's any problems.
